### ISSUE TITLE
Dang, you are getting good at this Corp!

### ISSUE THREAD

**Issue by macmeister1967** [corpnewt/FixHPET#1]
Just wondering what specific scenario is needed to run this script? I assume it is for use with OpenCore, but I am at a loss otherwise?!

Cheers

themacmeister

**Comment by corpnewt** [comment]
Hey there - I guess I must have missed this in my usual flow of info!  Sorry about the massive delay in this response!

> I assume it is for use with OpenCore, but I am at a loss otherwise?!

Yep!  I wrote this script after getting OpenCore booting with my laptop which has some IRQ issues (Goldfish64 helped walk me through this process manually).  I figured that automating it would be pretty helpful in the future for others.  Mind you - nothing beats understanding it yourself, but it makes setup a little easier.

-CorpNewt
